version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

jobs:
  build-and-deploy:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Set up Docker Buildx
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --use
      - run:
          name: Log in to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Build and Push Docker image
          command: |
            docker build -t my-app .
            docker tag my-app $DOCKER_USERNAME/my-app:latest
            docker push $DOCKER_USERNAME/my-app:latest
      - run:
          name: Deploy to Render
          environment:
            RENDER_API_KEY: $RENDER_API_KEY
            GOOGLE_API_KEY: $GOOGLE_API_KEY
          command: |
            curl -X POST -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Accept: application/json" \
            -d '{}' \
            https://api.render.com/v1/services/${SERVICE_ID}/deploys

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
